/**
 * Creating a sidebar enables you to:
- create an ordered group of docs
- render a sidebar for each doc of that group
- provide next/previous navigation

The sidebars can be generated from the filesystem, or explicitly defined here.

Create as many sidebars as you want.
 */

// @ts-check

/**
 * 一级导航 7 栏（2026-10-07 D5 重合并后）：
 *   DevSecOps（含 09-Compliance）· 红蓝攻防（含原 Penetration 四层）· 工业控制 ·
 *   电子取证 · 靶场与实验 · 证书 · CheatSheet
 * 合并是物理的（目录已经并到同一个父级），所以每个 sidebar 仍然只挂一条 autogenerated。
 * 若将来只想再收一栏而不想动目录，可以把两条 dirName 挂进同一个 sidebar —— 实测可行、
 * URL 不变、能单独回滚；本次没走那条路是因为要的是目录归属也一起收敛。
 */

/** @type {import('@docusaurus/plugin-content-docs').SidebarsConfig} */
const sidebars = {
    DevSecOps_Sidebar: [
        {
            type: 'autogenerated',
            dirName: 'DevSecOps'
        }
    ],
    AttackDefense_Sidebar: [
        {
            type: 'autogenerated',
            dirName: 'Attack-Defense'
        }
    ],
    ICS_Sidebar: [
        {
            type: 'autogenerated',
            dirName: 'ICS'
        }
    ],
    Forensic_Sidebar: [
        {
            type: 'autogenerated',
            dirName: 'Forensic'
        }
    ],
    Lab_Sidebar: [
        {
            type: 'autogenerated',
            dirName: 'Lab'
        }
    ],
    Certificate_Sidebar: [
        {
            type: 'autogenerated',
            dirName: 'Certificate'
        }
    ],
    CheatSheet_Sidebar: [
        {
            type: 'autogenerated',
            dirName: 'CheatSheet'
        }
    ]
};

module.exports = sidebars;
